---
- name: Automatizar copias de seguridad
  hosts: all
  become: yes
  tasks:
    - name: Crear directorio de backups
      file:
        path: /backups
        state: directory
        mode: '0755'

    - name: Crear backup de la base de datos
      command: mysqldump -u root -pPassword123 database > /backups/db_backup.sql