---
- name: Crear usuarios y grupos
  hosts: all
  become: yes
  tasks:
    - name: Crear grupo 'developers'
      group:
        name: developers
        state: present

    - name: Crear usuario 'john'
      user:
        name: john
        group: developers
        password: "{{ 'password123' | password_hash('sha512') }}"